version: '3'

# racik komposisi server
services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./laravel2:/var/www/html
      - ./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mywebapp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - mywebapp

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mywebappdb
      - MYSQL_USER=mywebappuser
      - MYSQL_PASSWORD=mywebappsecret
      - MYSQL_ROOT_PASSWORD=mywebappsecret
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - mywebapp

  php:
    build: ./dockerfiles
    container_name: php
    depends_on:
      - db
    volumes:
      - ./laravel2:/var/www/html
      - ./dockerfiles/bin/prj-build.sh:/var/www/html/prj-build.sh
      - ./dockerfiles/bin/prj-clean.sh:/var/www/html/prj-clean.sh
    ports:
      - "9000:9000"
    networks:
      - mywebapp

networks:
  mywebapp: